document.querySelectorAll('.lab-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.lab-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.lab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.lab).classList.add('active')}));
const fmt=x=>Number.isFinite(x)?(+x.toFixed(4)).toString():String(x);
function axes(c,xmax,ymax){const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const X=x=>50+x/xmax*(w-75),Y=y=>h-35-y/ymax*(h-60);ctx.strokeStyle='#cbd5e1';ctx.beginPath();ctx.moveTo(50,20);ctx.lineTo(50,h-35);ctx.lineTo(w-20,h-35);ctx.stroke();return{ctx,X,Y,w,h}}
function linePlot(c,series,xmax,ymax){const A=axes(c,xmax,ymax);for(const s of series){A.ctx.strokeStyle=s.color;A.ctx.lineWidth=2.4;A.ctx.beginPath();s.data.forEach((p,i)=>i?A.ctx.lineTo(A.X(p.x),A.Y(p.y)):A.ctx.moveTo(A.X(p.x),A.Y(p.y)));A.ctx.stroke()}return A}
function runExp(){const p0=+document.getElementById('exp-p0').value,r=+document.getElementById('exp-r').value,T=+document.getElementById('exp-t').value;const data=[];for(let i=0;i<=200;i++){const t=T*i/200;data.push({x:t,y:p0*Math.exp(r*t)})}const final=data.at(-1).y;document.getElementById('exp-summary').innerHTML='P('+fmt(T)+') ≈ <b>'+fmt(final)+'</b><br>Ikki baravar bo‘lish vaqti ≈ <b>'+fmt(Math.log(2)/r)+'</b>';linePlot(document.getElementById('exp-canvas'),[{data,color:'#2563eb'}],T,Math.max(...data.map(p=>p.y))*1.08);document.getElementById('exp-note').innerHTML='<b>Model nimani aytyapti?</b> Har bir nuqtada qiyalik rP ga teng; P kattalashgani sari o‘sish ham tezlashadi.'}
function runLogistic(){const p0=+document.getElementById('log-p0').value,r=+document.getElementById('log-r').value,K=+document.getElementById('log-k').value,T=+document.getElementById('log-t').value;const log=[],exp=[];for(let i=0;i<=250;i++){const t=T*i/250;const p=K/(1+((K-p0)/p0)*Math.exp(-r*t));log.push({x:t,y:p});exp.push({x:t,y:p0*Math.exp(r*t)})}const half=K/2;let closest=log.reduce((a,b)=>Math.abs(b.y-half)<Math.abs(a.y-half)?b:a);document.getElementById('log-summary').innerHTML='P('+fmt(T)+') ≈ <b>'+fmt(log.at(-1).y)+'</b><br>K/2 ga yaqin vaqt ≈ <b>'+fmt(closest.x)+'</b>';linePlot(document.getElementById('log-canvas'),[{data:log,color:'#2563eb'},{data:exp,color:'#ef4444'}],T,Math.max(K,Math.min(exp.at(-1).y,K*2))*1.08);document.getElementById('log-note').innerHTML='<b>Ko‘k:</b> logistik model. <b>Qizil:</b> cheklovsiz eksponensial. P K ga yaqinlashganda 1−P/K faktori o‘sishni so‘ndiradi.'}
function runSIR(){const N=+document.getElementById('sir-n').value,I0=+document.getElementById('sir-i0').value,beta=+document.getElementById('sir-beta').value,gamma=+document.getElementById('sir-gamma').value,T=+document.getElementById('sir-t').value,dt=.1;let S=N-I0,I=I0,R=0,t=0;const s=[],i=[],r=[];let peak={t:0,I};while(t<=T){s.push({x:t,y:S});i.push({x:t,y:I});r.push({x:t,y:R});if(I>peak.I)peak={t,I};const dS=-beta*S*I/N,dI=beta*S*I/N-gamma*I,dR=gamma*I;S+=dS*dt;I+=dI*dt;R+=dR*dt;t+=dt}document.getElementById('sir-summary').innerHTML='R₀≈β/γ=<b>'+fmt(beta/gamma)+'</b><br>Infeksiya cho‘qqisi ≈ <b>'+fmt(peak.I)+'</b> kishi, '+fmt(peak.t)+'-kun';linePlot(document.getElementById('sir-canvas'),[{data:s,color:'#2563eb'},{data:i,color:'#ef4444'},{data:r,color:'#16a34a'}],T,N*1.03);document.getElementById('sir-note').innerHTML='<b>Ko‘k S</b> — moyil, <b>qizil I</b> — infeksiyalangan, <b>yashil R</b> — chiqqan. Bu ta’limiy matematik model, tibbiy bashorat vositasi emas.'}
function buildModelCard(){const g=id=>document.getElementById(id).value.trim()||'—';const box=document.getElementById('model-card');box.classList.remove('hidden');box.innerHTML='<h3>Model kartasi</h3><dl><dt>Muammo</dt><dd>'+g('w-problem')+'</dd><dt>O‘zgaruvchi</dt><dd>'+g('w-vars')+'</dd><dt>Farazlar</dt><dd>'+g('w-assumptions')+'</dd><dt>Parametrlar</dt><dd>'+g('w-params')+'</dd><dt>Tenglama</dt><dd>'+g('w-eq')+'</dd><dt>Validatsiya</dt><dd>'+g('w-check')+'</dd></dl><p><b>Keyingi savol:</b> Model qaysi sharoitda ishlamay qoladi? Shu failure mode modelning eng muhim qismidir.</p>'}
runExp();runLogistic();runSIR();
const customExamples={
  decay:{eq:'-k*y',params:'k=0.3',y0:100,t:20,h:.05},
  logistic:{eq:'r*y*(1-y/K)',params:'r=0.4, K=100',y0:5,t:20,h:.05},
  harvest:{eq:'r*y*(1-y/K)-H',params:'r=0.5, K=120, H=8',y0:30,t:25,h:.05},
  forcing:{eq:'-k*y + A*sin(w*t)',params:'k=0.4, A=2, w=1.5',y0:0,t:25,h:.03}
};
function loadCustom(k){const q=customExamples[k];document.getElementById('custom-eq').value=q.eq;document.getElementById('custom-params').value=q.params;document.getElementById('custom-y0').value=q.y0;document.getElementById('custom-t').value=q.t;document.getElementById('custom-h').value=q.h}
function parseParamString(s){const out={};for(const part of s.split(',')){if(!part.trim())continue;const [k,v]=part.split('=').map(x=>x.trim());if(!/^[A-Za-z_]\w*$/.test(k)||!Number.isFinite(+v))throw Error('Parametr noto‘g‘ri: '+part);out[k]=+v}return out}
function compileModelExpr(raw,params){let expr=String(raw).trim().replace(/\^/g,'**');const names=['t','y',...Object.keys(params),'sin','cos','tan','exp','log','sqrt','abs','PI','E'];const ids=expr.match(/[A-Za-z_]\w*/g)||[];for(const id of ids)if(!names.includes(id))throw Error('Noma’lum belgi: '+id);const fn=new Function(...names,'return ('+expr+')');const vals=[...Object.values(params),Math.sin,Math.cos,Math.tan,Math.exp,Math.log,Math.sqrt,Math.abs,Math.PI,Math.E];return(t,y)=>fn(t,y,...vals)}
function simulateScalarODE(f,y0,T,h,method){let t=0,y=y0;const rows=[{t,y}];const max=100000;for(let k=0;k<max&&t<T-1e-12;k++){const hh=Math.min(h,T-t);let yn;if(method==='euler')yn=y+hh*f(t,y);else{const k1=f(t,y),k2=f(t+hh/2,y+hh*k1/2),k3=f(t+hh/2,y+hh*k2/2),k4=f(t+hh,y+hh*k3);yn=y+hh*(k1+2*k2+2*k3+k4)/6}if(!Number.isFinite(yn)||Math.abs(yn)>1e12)throw Error('Yechim sonli sohadan chiqib ketdi. Model yoki h ni tekshiring.');t+=hh;y=yn;rows.push({t,y})}return rows}
function runCustomModel(){try{const eq=document.getElementById('custom-eq').value,params=parseParamString(document.getElementById('custom-params').value),y0=+document.getElementById('custom-y0').value,T=+document.getElementById('custom-t').value,h=+document.getElementById('custom-h').value,method=document.getElementById('custom-method').value;if(!(T>0&&h>0))throw Error('T va h musbat bo‘lishi kerak.');const f=compileModelExpr(eq,params),rows=simulateScalarODE(f,y0,T,h,method);const ymin=Math.min(0,...rows.map(p=>p.y)),ymax=Math.max(1,...rows.map(p=>p.y));drawFlexiblePlot(document.getElementById('custom-canvas'),[{data:rows.map(p=>({x:p.t,y:p.y})),color:'#2563eb'}],0,T,ymin,ymax);document.getElementById('custom-summary').innerHTML='<b>'+method.toUpperCase()+'</b><br>y('+fmt(T)+') ≈ <b>'+fmt(rows.at(-1).y)+'</b><br>Qadamlar: '+(rows.length-1);document.getElementById('custom-note').innerHTML='<b>Model:</b> y′='+eq+'<br><b>Parametrlar:</b> '+Object.entries(params).map(([k,v])=>k+'='+v).join(', ')+'. Parametrlarni o‘zgartirib trayektoriya sezgirligini sinang.';const sample=rows.filter((_,i)=>i===0||i===rows.length-1||i%Math.max(1,Math.floor(rows.length/8))===0).slice(0,10);document.getElementById('custom-table').innerHTML='<table><tr><th>t</th><th>y</th><th>dy/dt</th></tr>'+sample.map(p=>'<tr><td>'+fmt(p.t)+'</td><td>'+fmt(p.y)+'</td><td>'+fmt(f(p.t,p.y))+'</td></tr>').join('')+'</table>'}catch(e){document.getElementById('custom-summary').innerHTML='<span style="color:#991b1b"><b>Xato:</b> '+e.message+'</span>'}}
function drawFlexiblePlot(c,series,xmin,xmax,ymin,ymax){const ctx=c.getContext('2d'),w=c.width,h=c.height;if(ymin===ymax){ymin--;ymax++}const pad=(ymax-ymin)*.08;ymin-=pad;ymax+=pad;ctx.clearRect(0,0,w,h);const X=x=>50+(x-xmin)/(xmax-xmin)*(w-75),Y=y=>h-35-(y-ymin)/(ymax-ymin)*(h-60);ctx.strokeStyle='#cbd5e1';ctx.beginPath();ctx.moveTo(50,20);ctx.lineTo(50,h-35);ctx.lineTo(w-20,h-35);ctx.stroke();for(const s of series){ctx.strokeStyle=s.color;ctx.lineWidth=2.4;ctx.beginPath();s.data.forEach((p,i)=>i?ctx.lineTo(X(p.x),Y(p.y)):ctx.moveTo(X(p.x),Y(p.y)));ctx.stroke()}}
