const KEY='ilm-mizan-mathlab-progress-v1',PROJECT_KEY='ilm-mizan-mathlab-research-project-v1';
function store(){try{return JSON.parse(localStorage.getItem(KEY))||{events:[],snapshots:[]}}catch{return{events:[],snapshots:[]}}}
function esc(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function dl(name,text,type){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type}));a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),600)}
function project(){return{title:r('r-title'),question:r('r-question'),hypothesis:r('r-hypothesis'),independent:r('r-independent'),dependent:r('r-dependent'),controls:r('r-controls'),method:r('r-method'),limitations:r('r-limitations'),format:r('r-format')}}
function r(id){return document.getElementById(id).value.trim()}
function saveProject(){localStorage.setItem(PROJECT_KEY,JSON.stringify(project()));toast('Research loyiha saqlandi')}
function loadProject(){try{const p=JSON.parse(localStorage.getItem(PROJECT_KEY))||{};for(const [k,id] of Object.entries({title:'r-title',question:'r-question',hypothesis:'r-hypothesis',independent:'r-independent',dependent:'r-dependent',controls:'r-controls',method:'r-method',limitations:'r-limitations',format:'r-format'}))if(p[k]!=null)document.getElementById(id).value=p[k]}catch{}}
function toast(t){const n=document.createElement('div');n.textContent=t;n.style='position:fixed;right:18px;bottom:18px;background:#166534;color:white;padding:10px 13px;border-radius:9px;font:700 12px system-ui;z-index:9999';document.body.appendChild(n);setTimeout(()=>n.remove(),1300)}
function selected(){const ids=[...document.querySelectorAll('.rsnap:checked')].map(x=>x.value),sn=store().snapshots||[];return ids.map(id=>sn.find(x=>x.id===id)).filter(Boolean)}
function renderSnaps(){const sn=(store().snapshots||[]).slice().reverse();document.getElementById('research-snaps').innerHTML=sn.length?sn.map(s=>'<div class="snaprow"><input type="checkbox" class="rsnap" value="'+s.id+'" onchange="buildDataset()"><div><b>'+esc(s.module)+'</b> <span class="badge">'+esc(s.id)+'</span><br><small>'+new Date(s.time).toLocaleString()+(s.notebook?.tags?' · '+esc(s.notebook.tags):'')+'</small></div><a href="'+s.url+'?snapshot='+encodeURIComponent(s.id)+'">Ochish</a></div>').join(''):'<p>Hali snapshot yo‘q. Avval modullarda tajriba qilib “Saqlash” tugmasini bosing.</p>'}
function selectAllSnaps(){document.querySelectorAll('.rsnap').forEach(x=>x.checked=true);buildDataset()}
function clearSelection(){document.querySelectorAll('.rsnap').forEach(x=>x.checked=false);buildDataset()}
function flatSnapshot(s){const row={snapshot_id:s.id,time:s.time,module:s.module,url:s.url};for(const x of s.inputs||[])row['input:'+x.label]=x.value;(s.results||[]).forEach((x,i)=>row['result:'+(i+1)]=x);if(s.notebook){row.hypothesis=s.notebook.hypothesis||'';row.observation=s.notebook.observation||'';row.conclusion=s.notebook.conclusion||'';row.tags=s.notebook.tags||''}return row}
function datasetRows(){return selected().map(flatSnapshot)}
function buildDataset(){const rows=datasetRows(),keys=[...new Set(rows.flatMap(x=>Object.keys(x)))];document.getElementById('dataset-info').textContent=rows.length+' ta tajriba tanlandi · '+keys.length+' ta ustun';document.getElementById('dataset').innerHTML=rows.length?'<table class="table"><tr>'+keys.map(k=>'<th>'+esc(k)+'</th>').join('')+'</tr>'+rows.map(row=>'<tr>'+keys.map(k=>'<td>'+esc(row[k]??'')+'</td>').join('')+'</tr>').join('')+'</table>':'<p>Tajriba tanlanmagan.</p>';return{rows,keys}}
function csv(rows,keys){const q=v=>'"'+String(v??'').replaceAll('"','""')+'"';return keys.map(q).join(',')+'\n'+rows.map(r=>keys.map(k=>q(r[k])).join(',')).join('\n')}
function exportDatasetCSV(){const d=buildDataset();if(!d.rows.length)return alert('Snapshot tanlang.');dl('mathlab-research-dataset.csv',csv(d.rows,d.keys),'text/csv')}
function exportReproJSON(){const snaps=selected();if(!snaps.length)return alert('Snapshot tanlang.');dl('mathlab-reproducibility.json',JSON.stringify({project:project(),generated_at:new Date().toISOString(),platform:'ILM Mizan MathLab',snapshots:snaps},null,2),'application/json')}
function notebookSummary(snaps){return snaps.map((s,i)=>{const n=s.notebook||{};return '- Tajriba '+(i+1)+' ('+s.module+', '+s.id+'): '+(n.observation||'Kuzatuv hali yozilmagan.')+(n.conclusion?' Xulosa: '+n.conclusion:'')}).join('\n')}
function generateDraft(){const p=project(),sn=selected(),fmt=p.format;const title=p.title||'Tadqiqot nomi';const common='# '+title+'\n\n**Platforma:** ILM Mizan MathLab\n**Tajriba soni:** '+sn.length+'\n**Generatsiya sanasi:** '+new Date().toLocaleString()+'\n\n';
let md=common;
if(fmt==='thesis')md+='## Dolzarblik\n[Tadqiqot nega muhimligini 3–5 jumlada yozing.]\n\n## Maqsad\n'+(p.question||'[Tadqiqot savolini kiriting]')+'\n\n## Gipoteza\n'+(p.hypothesis||'[Gipoteza]')+'\n\n## Metod\n'+(p.method||'[Metodologiya]')+'\n\n## Natijalar\n'+notebookSummary(sn)+'\n\n## Xulosa\n[Dataset tahlilidan keyin asosiy natijani yozing.]\n';
else if(fmt==='article')md+='## Annotatsiya\n[Maqsad, metod, asosiy sonli natija, xulosa — 150–250 so‘z.]\n\n## 1. Kirish\n**Tadqiqot savoli:** '+(p.question||'—')+'\n\n**Gipoteza:** '+(p.hypothesis||'—')+'\n\n## 2. Metodologiya\n**Mustaqil o‘zgaruvchi:** '+(p.independent||'—')+'\n**Bog‘liq o‘zgaruvchi:** '+(p.dependent||'—')+'\n**Nazorat shartlari:** '+(p.controls||'—')+'\n\n'+(p.method||'[Tajriba protokoli]')+'\n\n## 3. Natijalar\n'+notebookSummary(sn)+'\n\n[Bu yerga CSV datasetdan jadval, o‘rtacha, dispersion/xatolik va zarur statistik testlar qo‘shiladi.]\n\n## 4. Muhokama\n[Hipoteza qo‘llandimi? Nega? Boshqa usullar bilan taqqoslang.]\n\n## 5. Cheklovlar\n'+(p.limitations||'[Threats to validity]')+'\n\n## 6. Xulosa\n[Faqat real natijadan kelib chiqadigan xulosa.]\n\n## Reproduksiya\nSnapshot IDlar: '+sn.map(s=>s.id).join(', ')+'\n';
else md+='## Ishning maqsadi\n'+(p.question||'—')+'\n\n## Gipoteza\n'+(p.hypothesis||'—')+'\n\n## Jihoz / platforma\nILM Mizan MathLab, brauzer-local experiment snapshotlari.\n\n## Tajriba tartibi\n'+(p.method||'—')+'\n\n## Kuzatuvlar\n'+notebookSummary(sn)+'\n\n## Xulosa\n[O‘z xulosangiz.]\n';
document.getElementById('draft').textContent=md;saveProject();return md}
function exportMarkdown(){const md=generateDraft();dl('mathlab-research-draft.md',md,'text/markdown')}
loadProject();renderSnaps();buildDataset();