(()=>{const mod=(document.querySelector('.brand small')?.textContent||'').toLowerCase();
function style(){const s=document.createElement('style');s.textContent=`
.labplus{max-width:1220px;margin:0 auto 70px;padding:0 20px}.labplus-head{display:flex;justify-content:space-between;gap:12px;align-items:end;margin:28px 0 14px}.labplus-head h2{font-size:30px;margin:4px 0}.labplus-head p{margin:0;color:#64748b}.lp-grid{display:grid;grid-template-columns:1fr 1fr;gap:16px}.lp-card{background:#fff;border:1px solid #e2e8f0;border-radius:17px;padding:18px;box-shadow:0 8px 28px #0f172a0a}.lp-card h3{margin-top:0}.lp-card label{display:block;font:800 12px system-ui;color:#334155;margin:9px 0}.lp-card input,.lp-card textarea,.lp-card select{width:100%;padding:9px 10px;border:1px solid #cbd5e1;border-radius:9px;margin-top:4px;font:inherit}.lp-card textarea{min-height:90px}.lp-card button{border:0;border-radius:9px;padding:9px 12px;background:#2563eb;color:#fff;font-weight:800;cursor:pointer;margin:4px 5px 4px 0}.lp-out{margin-top:10px;padding:11px;background:#f8fafc;border:1px solid #e2e8f0;border-radius:10px;white-space:pre-wrap}.lp-note{padding:10px 12px;background:#fff7ed;border-left:4px solid #f59e0b;border-radius:9px;margin-top:10px}.lp-table{width:100%;border-collapse:collapse;font-size:12px}.lp-table td,.lp-table th{border:1px solid #e2e8f0;padding:6px;text-align:right}.lp-table th{background:#f8fafc}.lp-canvas{width:100%;border:1px solid #e2e8f0;border-radius:10px;margin-top:10px;background:white}.lp-badge{font-size:10px;letter-spacing:.12em;font-weight:900;color:#2563eb}@media(max-width:850px){.lp-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
const fmt=x=>Number.isFinite(x)?(+x.toFixed(6)).toString():String(x);
function host(title,sub,body){const s=document.createElement('section');s.className='labplus';s.innerHTML='<div class="labplus-head"><div><div class="lp-badge">LAB+ ACCESSORIES</div><h2>'+title+'</h2><p>'+sub+'</p></div></div>'+body;document.querySelector('main').appendChild(s);style()}
function plot(canvas,series,xmin,xmax,ymin,ymax){const c=document.getElementById(canvas),ctx=c.getContext('2d'),w=c.width,h=c.height;if(!(ymax>ymin)){ymin-=1;ymax+=1}const X=x=>45+(x-xmin)/(xmax-xmin)*(w-65),Y=y=>h-32-(y-ymin)/(ymax-ymin)*(h-52);ctx.clearRect(0,0,w,h);ctx.strokeStyle='#d1d5db';ctx.beginPath();ctx.moveTo(45,18);ctx.lineTo(45,h-32);ctx.lineTo(w-20,h-32);ctx.stroke();for(const s of series){ctx.strokeStyle=s.color;ctx.lineWidth=2.2;ctx.beginPath();s.data.forEach((p,i)=>i?ctx.lineTo(X(p.x),Y(p.y)):ctx.moveTo(X(p.x),Y(p.y)));ctx.stroke()}}
function safeFn(raw,vars=['x']){let s=String(raw).replace(/\^/g,'**').replace(/\bpi\b/gi,'PI');const allowed=[...vars,'sin','cos','tan','exp','log','sqrt','abs','PI','E'];for(const id of s.match(/[A-Za-z_]\w*/g)||[])if(!allowed.includes(id))throw Error('Noma’lum belgi: '+id);const fn=new Function(...allowed,'return ('+s+')');const tail=[Math.sin,Math.cos,Math.tan,Math.exp,Math.log,Math.sqrt,Math.abs,Math.PI,Math.E];return(...v)=>fn(...v,...tail)}
function functional(){
host('Funksional analiz — operator laboratoriyasi','Abstrakt tushunchalarni operatorlar, ortogonallik va iteratsiya orqali sinang.',`
<div class="lp-grid">
<div class="lp-card"><h3>2×2 chiziqli operator</h3>
<label>A11<input id="op-a" type="number" value="2"></label><label>A12<input id="op-b" type="number" value="1"></label><label>A21<input id="op-c" type="number" value="0"></label><label>A22<input id="op-d" type="number" value="0.5"></label>
<label>v=(x,y)<input id="op-v" value="1,1"></label><label>Iteratsiya soni<input id="op-n" type="number" value="8"></label>
<button onclick="lpOperator()">Operatorni sinash</button><div id="op-out" class="lp-out"></div></div>
<div class="lp-card"><h3>Gram–Schmidt ustaxonasi</h3>
<label>v₁<input id="gs-v1" value="1,1,0"></label><label>v₂<input id="gs-v2" value="1,0,1"></label>
<button onclick="lpGS()">Ortonormallashtir</button><div id="gs-out" class="lp-out"></div>
<div class="lp-note">Proyeksiya va ortogonallikni sonlarda tekshiring: q₁·q₂ ≈ 0, ‖qᵢ‖ ≈ 1.</div></div>
</div>`);
window.lpOperator=()=>{try{const a=+opA('op-a'),b=+opA('op-b'),c=+opA('op-c'),d=+opA('op-d'),v=document.getElementById('op-v').value.split(',').map(Number),n=+opA('op-n');let x=v[0],y=v[1],rows=[];const tr=a+d,det=a*d-b*c,disc=tr*tr-4*det;let ev=disc>=0?[(tr+Math.sqrt(disc))/2,(tr-Math.sqrt(disc))/2]:['complex','complex'];for(let k=0;k<=n;k++){rows.push([k,x,y,Math.hypot(x,y)]);[x,y]=[a*x+b*y,c*x+d*y]}document.getElementById('op-out').innerHTML='trace='+fmt(tr)+', det='+fmt(det)+'<br>eigenvalues ≈ '+ev.map(fmt).join(', ')+'<br><br><table class="lp-table"><tr><th>k</th><th>x</th><th>y</th><th>‖Aᵏv‖₂</th></tr>'+rows.map(r=>'<tr>'+r.map(z=>'<td>'+fmt(z)+'</td>').join('')+'</tr>').join('')+'</table>'}catch(e){opOut(e,'op-out')}};
window.lpGS=()=>{try{const p=s=>s.split(',').map(Number),u=p(document.getElementById('gs-v1').value),v=p(document.getElementById('gs-v2').value);if(u.length!==v.length)throw Error('O‘lchamlar teng bo‘lsin');const dot=(x,y)=>x.reduce((s,z,i)=>s+z*y[i],0),norm=x=>Math.sqrt(dot(x,x)),q1=u.map(z=>z/norm(u)),coef=dot(v,q1),w=v.map((z,i)=>z-coef*q1[i]),q2=w.map(z=>z/norm(w));document.getElementById('gs-out').textContent='q₁ = ('+q1.map(fmt).join(', ')+')\nq₂ = ('+q2.map(fmt).join(', ')+')\nq₁·q₂ = '+fmt(dot(q1,q2))+'\n‖q₁‖ = '+fmt(norm(q1))+', ‖q₂‖ = '+fmt(norm(q2))}catch(e){opOut(e,'gs-out')}};
}
function opA(id){return document.getElementById(id).value}function opOut(e,id){document.getElementById(id).textContent='Xato: '+e.message}
function pde(){
host('PDE — Fourier & stability lab','Yechimni faqat animatsiya emas, spektr va sonli barqarorlik orqali ham tahlil qiling.',`
<div class="lp-grid">
<div class="lp-card"><h3>Fourier sine series</h3><label>f(x), 0≤x≤1<input id="fs-f" value="x*(1-x)*4"></label><label>Modalar N<input id="fs-n" type="number" min="1" max="30" value="6"></label><button onclick="lpFourier()">Qatorni qur</button><div id="fs-out" class="lp-out"></div><canvas id="fs-canvas" class="lp-canvas" width="720" height="360"></canvas></div>
<div class="lp-card"><h3>Finite-difference barqarorlik kalkulyatori</h3><label>α<input id="st-alpha" type="number" step=".01" value=".1"></label><label>Δx<input id="st-dx" type="number" step=".001" value=".025"></label><label>Δt<input id="st-dt" type="number" step=".0001" value=".001"></label><button onclick="lpStability()">Tekshir</button><div id="st-out" class="lp-out"></div><div class="lp-note">Heat explicit sxemada r=αΔt/Δx² ≤ 1/2. Wave explicit sxemada CFL=cΔt/Δx ≤ 1.</div></div>
</div>`);
window.lpFourier=()=>{try{const f=safeFn(document.getElementById('fs-f').value),N=+document.getElementById('fs-n').value,coef=[];for(let n=1;n<=N;n++){let sum=0,M=2000,h=1/M;for(let i=0;i<=M;i++){const x=i*h,w=(i===0||i===M)?.5:1;sum+=w*f(x)*Math.sin(n*Math.PI*x)}coef.push(2*sum*h)}const orig=[],approx=[];let err=0;for(let i=0;i<=400;i++){const x=i/400,y=f(x),z=coef.reduce((s,b,n)=>s+b*Math.sin((n+1)*Math.PI*x),0);orig.push({x,y});approx.push({x,y:z});err+=(y-z)**2}const vals=[...orig,...approx].map(p=>p.y);plot('fs-canvas',[{data:orig,color:'#111827'},{data:approx,color:'#2563eb'}],0,1,Math.min(...vals),Math.max(...vals));document.getElementById('fs-out').innerHTML='MSE ≈ <b>'+fmt(err/401)+'</b><br>bₙ: '+coef.map((b,i)=>'b'+(i+1)+'='+fmt(b)).join(', ')}catch(e){opOut(e,'fs-out')}};
window.lpStability=()=>{const a=+opA('st-alpha'),dx=+opA('st-dx'),dt=+opA('st-dt'),r=a*dt/(dx*dx);document.getElementById('st-out').innerHTML='r = <b>'+fmt(r)+'</b><br>'+(r<=.5?'✅ Heat explicit sxema barqaror zona.':'⚠️ r>0.5 — Δt ni kamaytiring yoki Δx ni kattalashtiring.')+'<br>Maksimal Δt ≈ <b>'+fmt(.5*dx*dx/a)+'</b>'};
}
function modeling(){
host('Modellashtirish — sensitivity lab','Bitta natija emas: parametr o‘zgarganda model qanday javob berishini ko‘ring.',`
<div class="lp-grid">
<div class="lp-card"><h3>Parameter sweep</h3><label>Model y′=<input id="sw-eq" value="r*y*(1-y/K)"></label><label>Parametrlar<input id="sw-params" value="r=0.4,K=100"></label><label>Sweep parametri<input id="sw-name" value="r"></label><label>Start<input id="sw-start" type="number" value=".1"></label><label>End<input id="sw-end" type="number" value="1"></label><label>Nuqtalar<input id="sw-count" type="number" value="10"></label><label>y₀<input id="sw-y0" type="number" value="5"></label><label>T<input id="sw-T" type="number" value="20"></label><button onclick="lpSweep()">Sensitivity</button><div id="sw-out" class="lp-out"></div><canvas id="sw-canvas" class="lp-canvas" width="720" height="360"></canvas></div>
<div class="lp-card"><h3>Equilibrium finder</h3><label>y′=f(y)<input id="eq-f" value="0.4*y*(1-y/100)"></label><label>y min<input id="eq-min" type="number" value="-10"></label><label>y max<input id="eq-max" type="number" value="130"></label><button onclick="lpEquilibria()">Muvozanatlarni top</button><div id="eq-out" class="lp-out"></div><div class="lp-note">f(y*)=0 bo‘lsa equilibrium. f′(y*)<0 — lokal barqaror, f′(y*)>0 — beqaror.</div></div>
</div>`);
const parseP=s=>Object.fromEntries(s.split(',').map(z=>z.split('=').map(x=>x.trim())).filter(x=>x[0]).map(([k,v])=>[k,+v]));
const compile=(raw,p)=>{let s=raw.replace(/\^/g,'**');const names=['t','y',...Object.keys(p),'sin','cos','exp','sqrt','abs'];const fn=new Function(...names,'return ('+s+')');const tail=[Math.sin,Math.cos,Math.exp,Math.sqrt,Math.abs];return(t,y)=>fn(t,y,...Object.values(p),...tail)};
const solve=(f,y0,T)=>{let y=y0,t=0,h=Math.max(.001,T/800);while(t<T){h=Math.min(h,T-t);const k1=f(t,y),k2=f(t+h/2,y+h*k1/2),k3=f(t+h/2,y+h*k2/2),k4=f(t+h,y+h*k3);y+=h*(k1+2*k2+2*k3+k4)/6;t+=h;if(!Number.isFinite(y))break}return y};
window.lpSweep=()=>{try{const base=parseP(opA('sw-params')),name=opA('sw-name'),a=+opA('sw-start'),b=+opA('sw-end'),n=Math.max(2,+opA('sw-count')),y0=+opA('sw-y0'),T=+opA('sw-T'),data=[];for(let i=0;i<n;i++){const v=a+(b-a)*i/(n-1),p={...base,[name]:v},f=compile(opA('sw-eq'),p);data.push({x:v,y:solve(f,y0,T)})}const ys=data.map(p=>p.y);plot('sw-canvas',[{data,color:'#2563eb'}],a,b,Math.min(...ys),Math.max(...ys));document.getElementById('sw-out').innerHTML='<table class="lp-table"><tr><th>'+name+'</th><th>y(T)</th></tr>'+data.map(p=>'<tr><td>'+fmt(p.x)+'</td><td>'+fmt(p.y)+'</td></tr>').join('')+'</table>'}catch(e){opOut(e,'sw-out')}};
window.lpEquilibria=()=>{try{const f=safeFn(opA('eq-f'),['y']),a=+opA('eq-min'),b=+opA('eq-max'),roots=[];let px=a,py=f(a);for(let i=1;i<=1500;i++){const x=a+(b-a)*i/1500,y=f(x);if(Number.isFinite(py)&&Number.isFinite(y)&&py*y<=0){let l=px,r=x;for(let k=0;k<40;k++){const m=(l+r)/2;if(f(l)*f(m)<=0)r=m;else l=m}const q=(l+r)/2;if(!roots.some(z=>Math.abs(z-q)<1e-4))roots.push(q)}px=x;py=y}document.getElementById('eq-out').innerHTML=roots.length?roots.map(r=>{const h=1e-5*(1+Math.abs(r)),d=(f(r+h)-f(r-h))/(2*h);return 'y*≈<b>'+fmt(r)+'</b> — '+(d<0?'barqaror':'beqaror')+' (f′≈'+fmt(d)+')'}).join('<br>'):'Muvozanat topilmadi.'}catch(e){opOut(e,'eq-out')}};
}
function python(){
host('Python — experiment bench','Kod faqat ishlamasin: input sweep, benchmark va testlar bilan tajriba qiling.',`
<div class="lp-grid">
<div class="lp-card"><h3>Parameter experiment</h3><p>Real Python editor ichidagi kodda <code>PARAM</code> nomli o‘zgaruvchini ishlating. Lab+ uni qiymatlar ro‘yxati bilan qayta-qayta bajaradi.</p><label>PARAM qiymatlari<input id="px-values" value="1,2,5,10"></label><button onclick="lpPyExperiment()">Run sweep</button><div id="px-out" class="lp-out"></div></div>
<div class="lp-card"><h3>Micro-benchmark</h3><label>Takrorlash soni<input id="pb-n" type="number" value="10"></label><button onclick="lpPyBench()">Joriy kodni benchmark</button><div id="pb-out" class="lp-out"></div><div class="lp-note">Brauzer/Pyodide benchmark absolut server tezligi emas; algoritmlarni bir xil muhitda nisbiy taqqoslash uchun foydali.</div></div>
</div>`);
window.lpPyExperiment=async()=>{try{if(typeof getPyodideRuntime!=='function')throw Error('Python runtime topilmadi');const py=await getPyodideRuntime(),code=document.getElementById('real-code').value,vals=opA('px-values').split(',').map(Number),rows=[];for(const v of vals){let out='';py.setStdout({batched:s=>out+=s+'\n'});await py.loadPackagesFromImports(code);const t=performance.now();await py.runPythonAsync('PARAM='+JSON.stringify(v)+'\n'+code);rows.push([v,(performance.now()-t).toFixed(1),out.trim().slice(-200)])}document.getElementById('px-out').innerHTML='<table class="lp-table"><tr><th>PARAM</th><th>ms</th><th>output</th></tr>'+rows.map(r=>'<tr><td>'+r[0]+'</td><td>'+r[1]+'</td><td>'+String(r[2]).replace(/[<>]/g,'')+'</td></tr>').join('')+'</table>'}catch(e){opOut(e,'px-out')}};
window.lpPyBench=async()=>{try{const py=await getPyodideRuntime(),code=document.getElementById('real-code').value,n=Math.max(1,+opA('pb-n'));await py.loadPackagesFromImports(code);const ts=[];py.setStdout({batched:()=>{}});for(let i=0;i<n;i++){const t=performance.now();await py.runPythonAsync(code);ts.push(performance.now()-t)}const avg=ts.reduce((a,b)=>a+b,0)/n;document.getElementById('pb-out').textContent='n='+n+'\nmean='+fmt(avg)+' ms\nmin='+fmt(Math.min(...ts))+' ms\nmax='+fmt(Math.max(...ts))+' ms'}catch(e){opOut(e,'pb-out')}};
}
function practice(){
host('Praktikum — challenge & error lab','Masala ishlashni statistik tajribaga aylantiring: aralash rejim va xatolar jurnali.',`
<div class="lp-grid">
<div class="lp-card"><h3>Mixed challenge</h3><label>Masalalar soni<input id="ch-n" type="number" min="3" max="30" value="10"></label><label>Qiyinlik<select id="ch-d"><option value="easy">Oson</option><option value="medium" selected>O‘rta</option><option value="hard">Qiyin</option></select></label><button onclick="lpStartChallenge()">Challenge boshlash</button><div id="ch-out" class="lp-out">Boshlash tugmasini bosing.</div></div>
<div class="lp-card"><h3>Xato jurnali</h3><div id="err-log" class="lp-out">Hali xato qayd etilmagan.</div><button onclick="lpClearErrors()">Jurnalni tozalash</button><div class="lp-note">Bir xil xato turi qayta-qayta chiqsa, aynan o‘sha pattern bo‘yicha mashq qilish kerak.</div></div>
</div>`);
let ch=null;const oldCheck=window.checkAttempt;window.checkAttempt=function(){const before=session.correct;oldCheck();if(session.correct===before){const log=JSON.parse(localStorage.getItem('mathlab-error-log')||'[]');log.push({time:new Date().toISOString(),topic,problem:current?.q||'',pattern:current?.pattern||'',mistake:current?.mistake||''});localStorage.setItem('mathlab-error-log',JSON.stringify(log.slice(-100)));renderErr()}if(ch){ch.done++;if(session.correct>before)ch.ok++;renderCh();if(ch.done<ch.total){topic=ch.topics[Math.floor(Math.random()*ch.topics.length)];document.querySelectorAll('.topic').forEach(b=>b.classList.toggle('active',b.dataset.topic===topic));document.getElementById('difficulty').value=ch.d;newProblem()}}};
function renderErr(){const log=JSON.parse(localStorage.getItem('mathlab-error-log')||'[]');document.getElementById('err-log').innerHTML=log.length?log.slice(-15).reverse().map(x=>'<div><b>'+x.topic+'</b>: '+x.mistake+'<br><small>'+new Date(x.time).toLocaleString()+'</small></div><hr>').join(''):'Hali xato qayd etilmagan.'}
function renderCh(){document.getElementById('ch-out').innerHTML=ch?'Bajarildi: <b>'+ch.done+'/'+ch.total+'</b><br>To‘g‘ri: <b>'+ch.ok+'</b><br>Aniqlik: <b>'+fmt(ch.done?100*ch.ok/ch.done:0)+'%</b>':''}
window.lpStartChallenge=()=>{ch={total:+opA('ch-n'),done:0,ok:0,d:opA('ch-d'),topics:['factor','quadratic','sequence','function']};topic=ch.topics[Math.floor(Math.random()*ch.topics.length)];document.querySelectorAll('.topic').forEach(b=>b.classList.toggle('active',b.dataset.topic===topic));document.getElementById('difficulty').value=ch.d;newProblem();renderCh()};
window.lpClearErrors=()=>{localStorage.removeItem('mathlab-error-log');renderErr()};renderErr();
}
document.addEventListener('DOMContentLoaded',()=>{if(mod.includes('funksional'))functional();else if(mod.includes('fizika'))pde();else if(mod.includes('modellashtirish'))modeling();else if(mod.includes('python'))python();else if(mod.includes('masalalar'))practice()});
})();