document.querySelectorAll('.lab-tab').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.lab-tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.lab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.getElementById(b.dataset.lab).classList.add('active')}));
const fmt=x=>Number.isFinite(x)?(+x.toFixed(5)).toString():String(x);
function classifyPDE(){const A=+document.getElementById('cl-a').value,B=+document.getElementById('cl-b').value,C=+document.getElementById('cl-c').value,D=B*B-A*C;const type=D<0?'Elliptik':D>0?'Giperbolik':'Parabolik';document.getElementById('class-summary').innerHTML='D = B² − AC = <b>'+fmt(D)+'</b><br>Turi: <b>'+type+'</b>';document.getElementById('class-note').innerHTML=type==='Elliptik'?'<b>Intuitsiya:</b> vaqt evolyutsiyasidan ko‘ra muvozanat konfiguratsiyasi muhim.':type==='Parabolik'?'<b>Intuitsiya:</b> boshlang‘ich holat vaqt o‘tishi bilan yoyilib/silliqlanib boradi.':'<b>Intuitsiya:</b> signal yoki tebranish chekli tezlikda tarqaladi.'}
function axes(c,ymin,ymax){const ctx=c.getContext('2d'),w=c.width,h=c.height;ctx.clearRect(0,0,w,h);const X=x=>48+x*(w-70),Y=y=>h-35-(y-ymin)/(ymax-ymin)*(h-58);ctx.strokeStyle='#cbd5e1';ctx.beginPath();ctx.moveTo(48,20);ctx.lineTo(48,h-35);ctx.lineTo(w-20,h-35);ctx.stroke();return{ctx,X,Y,w,h}}
function plotProfile(c,fn,ymin,ymax){const A=axes(c,ymin,ymax);A.ctx.strokeStyle='#2563eb';A.ctx.lineWidth=2.5;A.ctx.beginPath();for(let i=0;i<=500;i++){const x=i/500,y=fn(x);i?A.ctx.lineTo(A.X(x),A.Y(y)):A.ctx.moveTo(A.X(x),A.Y(y))}A.ctx.stroke()}
let heatTimer=null;
function heatProfile(x,t,alpha,amp,modes){let s=0;for(let n=1;n<=modes;n++){const bn=(n%2?1:-.45)/n;s+=amp*bn*Math.sin(n*Math.PI*x)*Math.exp(-alpha*n*n*Math.PI*Math.PI*t)}return s}
function drawHeat(){const a=+document.getElementById('heat-alpha').value,amp=+document.getElementById('heat-amp').value,m=Math.max(1,+document.getElementById('heat-modes').value),t=+document.getElementById('heat-time').value;plotProfile(document.getElementById('heat-canvas'),x=>heatProfile(x,t,a,amp,m),-amp*1.2,amp*1.2);document.getElementById('heat-summary').innerHTML='t = <b>'+fmt(t)+'</b><br>α = <b>'+fmt(a)+'</b>';document.getElementById('heat-note').innerHTML='<b>Ko‘ring:</b> yuqori chastotali modalar e^(−αn²π²t) sabab tezroq so‘nadi. Shuning uchun profil vaqt o‘tishi bilan silliqlashadi.'}
function playHeat(){if(heatTimer){clearInterval(heatTimer);heatTimer=null;return}let t=0;heatTimer=setInterval(()=>{t+=.05;if(t>5){clearInterval(heatTimer);heatTimer=null;return}document.getElementById('heat-time').value=t;drawHeat()},70)}
let waveTimer=null;
function drawWave(){const c=+document.getElementById('wave-c').value,amp=+document.getElementById('wave-amp').value,n=Math.max(1,+document.getElementById('wave-n').value),t=+document.getElementById('wave-time').value;plotProfile(document.getElementById('wave-canvas'),x=>amp*Math.sin(n*Math.PI*x)*Math.cos(n*Math.PI*c*t),-Math.abs(amp)*1.3,Math.abs(amp)*1.3);document.getElementById('wave-summary').innerHTML='n = <b>'+n+'</b><br>ω = nπc ≈ <b>'+fmt(n*Math.PI*c)+'</b>';document.getElementById('wave-note').innerHTML='<b>Geometrik ma’no:</b> tugunlar joyi moda n ga bog‘liq. Ideal modelda amplituda vaqt bilan so‘nmaydi; faqat ishora/faza o‘zgaradi.'}
function playWave(){if(waveTimer){clearInterval(waveTimer);waveTimer=null;return}let t=0;waveTimer=setInterval(()=>{t+=.05;if(t>10){clearInterval(waveTimer);waveTimer=null;return}document.getElementById('wave-time').value=t;drawWave()},55)}
function runLaplace(){const N=Math.max(6,Math.min(35,+document.getElementById('lap-n').value)),top=+document.getElementById('lap-top').value,bottom=+document.getElementById('lap-bottom').value,left=+document.getElementById('lap-left').value,right=+document.getElementById('lap-right').value,iters=Math.max(1,+document.getElementById('lap-iters').value);let u=Array.from({length:N},()=>Array(N).fill(0));for(let j=0;j<N;j++){u[0][j]=top;u[N-1][j]=bottom}for(let i=0;i<N;i++){u[i][0]=left;u[i][N-1]=right}for(let k=0;k<iters;k++){const v=u.map(r=>r.slice());for(let i=1;i<N-1;i++)for(let j=1;j<N-1;j++)v[i][j]=(u[i-1][j]+u[i+1][j]+u[i][j-1]+u[i][j+1])/4;u=v}drawHeatmap(u);document.getElementById('lap-summary').innerHTML='Iteratsiya: <b>'+iters+'</b><br>Markaz u ≈ <b>'+fmt(u[Math.floor(N/2)][Math.floor(N/2)])+'</b>';document.getElementById('lap-note').innerHTML='<b>Ma’no:</b> ichki nuqta qo‘shnilarining o‘rtachasi bo‘lib boradi — tizim chegaralar majburlagan muvozanat holatiga keladi.'}
function drawHeatmap(u){const c=document.getElementById('lap-canvas'),ctx=c.getContext('2d'),w=c.width,h=c.height,N=u.length,max=Math.max(...u.flat()),min=Math.min(...u.flat()),d=max-min||1,cw=w/N,ch=h/N;ctx.clearRect(0,0,w,h);for(let i=0;i<N;i++)for(let j=0;j<N;j++){const t=(u[i][j]-min)/d;ctx.fillStyle='rgb('+Math.floor(240*t+15)+','+Math.floor(80+110*(1-Math.abs(t-.5)*2))+','+Math.floor(240*(1-t)+15)+')';ctx.fillRect(j*cw,i*ch,cw+1,ch+1)}}
classifyPDE();drawHeat();drawWave();runLaplace();