const bank={
factor:[
{q:'x² + 5x + 6 ni ko‘paytuvchilarga ajrating.',goal:'Ikki binom ko‘paytmasi ko‘rinishiga keltiring.',answer:['(x+2)(x+3)','(x+3)(x+2)'],hints:['Yig‘indisi 5, ko‘paytmasi 6 bo‘lgan ikki sonni qidiring.','Bu sonlar 2 va 3.'],strategy:'x²+bx+c da m+n=b va mn=c bo‘ladigan m,n topiladi.',steps:['m+n=5 va mn=6 shartlarni yozamiz.','2+3=5 va 2·3=6.','x²+5x+6=(x+2)(x+3).'],pattern:'Kvadrat uchhad uchun yig‘indi/ko‘paytma juftligini tanish.',mistake:'Faqat ko‘paytmasi 6 bo‘lgan juftni tanlab, yig‘indini tekshirmaslik.',alternative:'Butun juftlik topilmasa diskriminant yoki ildizlardan foydalanish mumkin.'},
{q:'4x² - 9 ni ko‘paytuvchilarga ajrating.',goal:'Qisqa ko‘paytirish formulasini taning.',answer:['(2x-3)(2x+3)','(2x+3)(2x-3)'],hints:['Bu ikki kvadrat ayirmasiga o‘xshaydi.','a²-b²=(a-b)(a+b).'],strategy:'4x²=(2x)² va 9=3².',steps:['4x²−9=(2x)²−3².','a²−b²=(a−b)(a+b).','Natija: (2x−3)(2x+3).'],pattern:'Ikki kvadrat ayirmasi.',mistake:'a²−b² ni (a−b)² deb yuborish.',alternative:'Agar hadlar kvadrat bo‘lmasa umumiy ko‘paytuvchini ajrating.'}],
quadratic:[
{q:'x² - 7x + 12 = 0 tenglamani yeching.',goal:'Ildizlarni toping.',answer:['x=3,4','3,4','x1=3,x2=4','x1=4,x2=3'],hints:['Ko‘paytmasi 12, yig‘indisi -7 bo‘lgan sonlar kerak.','-3 va -4 ni sinang.'],strategy:'Tenglamani (x-a)(x-b)=0 ko‘rinishga keltirish mumkin.',steps:['x²−7x+12=(x−3)(x−4).','Ko‘paytma 0 bo‘lsa kamida bir ko‘paytuvchi 0.','x=3 yoki x=4.'],pattern:'Butun ildizli kvadrat tenglama.',mistake:'Ildizlar ishorasini ko‘paytuvchilardagi ishora bilan adashtirish.',alternative:'Ajralmasa D=b²−4ac formulasiga o‘ting.'},
{q:'2x² + x - 3 = 0 ni yeching.',goal:'Kvadrat tenglama ildizlarini toping.',answer:['x=1,-1.5','1,-1.5','x1=1,x2=-1.5'],hints:['D=b²−4ac ni hisoblang.','D=25, √D=5.'],strategy:'Umumiy kvadrat formula x=(-b±√D)/(2a).',steps:['a=2,b=1,c=−3.','D=1−4·2·(−3)=25.','x=(-1±5)/4.','x₁=1, x₂=−3/2.'],pattern:'Ajratish qiyin bo‘lsa diskriminant universal usul.',mistake:'c manfiy bo‘lganda −4ac ishorasini xato qilish.',alternative:'Vieta orqali ham tekshirish mumkin.'}],
sequence:[
{q:'2, 5, 8, 11, ... ketma-ketlikning 20-hadini toping.',goal:'Arifmetik progressiya formulasidan foydalaning.',answer:['59','a20=59'],hints:['Ayirma doim 3.','aₙ=a₁+(n−1)d.'],strategy:'Avval progressiya turini va d ni aniqlang.',steps:['a₁=2, d=3.','a₂₀=2+(20−1)·3.','a₂₀=59.'],pattern:'Doimiy ayirma → arifmetik progressiya.',mistake:'n o‘rniga n−1 ni unutish.',alternative:'Rekursiv qo‘shib borish mumkin, lekin formula tezroq.'}],
function:[
{q:'f(x)=2x²−3x+1 bo‘lsa, f(2) ni toping.',goal:'x o‘rniga berilgan sonni to‘g‘ri qo‘ying.',answer:['3','f(2)=3'],hints:['Har bir x o‘rniga 2 yozing.','2·2²−3·2+1.'],strategy:'Funksiya qiymati — formuladagi argumentni berilgan qiymat bilan almashtirish.',steps:['f(2)=2·(2²)−3·2+1.','=8−6+1.','=3.'],pattern:'Argumentni to‘liq almashtirish.',mistake:'Darajani yoki manfiy ishorani noto‘g‘ri qo‘llash.',alternative:'Jadval tuzib ham tekshirish mumkin.'}]
};

function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function nz(a,b){let x=0;while(x===0)x=ri(a,b);return x}
function signTerm(n){return n>=0?' + '+n:' - '+Math.abs(n)}
function makeFactor(d){
  if(d==='easy'){const a=ri(1,6),b=ri(1,6),s=a+b,p=a*b;return{q:'x² + '+s+'x + '+p+' ni ko‘paytuvchilarga ajrating.',goal:'Ikki binom ko‘paytmasi ko‘rinishiga keltiring.',answer:['(x+'+a+')(x+'+b+')','(x+'+b+')(x+'+a+')'],hints:['Yig‘indisi '+s+', ko‘paytmasi '+p+' bo‘lgan sonlarni toping.','Bu sonlar '+a+' va '+b+'.'],strategy:'x²+bx+c da m+n=b va mn=c.',steps:['m+n='+s+', mn='+p+'.',a+'+'+b+'='+s+' va '+a+'·'+b+'='+p+'.','Natija: (x+'+a+')(x+'+b+').'],pattern:'Yig‘indi/ko‘paytma juftligi.',mistake:'Faqat ko‘paytmani tekshirish.',alternative:'Butun juftlik chiqmasa diskriminantdan foydalaning.'}}
  if(d==='medium'){const a=nz(-7,7),b=nz(-7,7),s=-(a+b),p=a*b;const f1=(a>=0?'(x-'+a+')':'(x+'+(-a)+')'),f2=(b>=0?'(x-'+b+')':'(x+'+(-b)+')');return{q:'x² '+signTerm(s)+'x '+signTerm(p)+' ni ko‘paytuvchilarga ajrating.'.replace('+ -','- '),goal:'Ildizlar orqali binomlarga ajrating.',answer:[f1+f2,f2+f1],hints:['Ildizlari '+a+' va '+b+' bo‘lishi kerak.','(x-r₁)(x-r₂) formulasini ishlating.'],strategy:'r₁+r₂=-b, r₁r₂=c.',steps:['r₁='+a+', r₂='+b+'.','(x-r₁)(x-r₂).','Natija: '+f1+f2+'.'],pattern:'Vieta bilan ajratish.',mistake:'Ildiz ishorasini binom ishorasi bilan adashtirish.',alternative:'Diskriminant bilan ildizlarni tekshiring.'}}
  const m=ri(2,6),a=ri(1,7),b=ri(1,7),A=m*m,C=a*b,s=m*(a+b);return{q:A+'x² + '+s+'x + '+C+' ni ko‘paytuvchilarga ajrating.',goal:'Yetakchi koeffitsiyent 1 emas.',answer:['('+m+'x+'+a+')('+m+'x+'+b+')','('+m+'x+'+b+')('+m+'x+'+a+')'],hints:['Birinchi had ('+m+'x)².','O‘rta had '+m+'x·'+a+' + '+m+'x·'+b+'.'],strategy:'ac-usuli yoki guruhlash.',steps:[A+'x²+'+s+'x+'+C+'.','O‘rta hadni '+(m*a)+'x + '+(m*b)+'x ga ajrating.','Guruhlab: ('+m+'x+'+a+')('+m+'x+'+b+').'],pattern:'Yetakchi koeffitsiyentli uchhad.',mistake:'Faqat oxirgi had ko‘paytuvchilarini ko‘rish.',alternative:'Umumiy diskriminant formulasidan ildiz topib ajrating.'}}
function makeQuadratic(d){
  if(d==='easy'){const r1=ri(1,8),r2=ri(1,8),b=-(r1+r2),c=r1*r2;return{q:'x² '+signTerm(b)+'x '+signTerm(c)+' = 0 ni yeching.',goal:'Ikkita ildizni toping.',answer:['x='+r1+','+r2,r1+','+r2,'x1='+r1+',x2='+r2,'x1='+r2+',x2='+r1],hints:['Vieta ishlaydi.','Ildizlar yig‘indisi '+(r1+r2)+', ko‘paytmasi '+c+'.'],strategy:'Ajratib nol ko‘paytma qoidasini ishlating.',steps:['(x-'+r1+')(x-'+r2+')=0.','x-'+r1+'=0 yoki x-'+r2+'=0.','x='+r1+', '+r2+'.'],pattern:'Butun ildizli kvadrat.',mistake:'Binomdagi ishorani xato talqin qilish.',alternative:'D formulasiga o‘ting.'}}
  const a=d==='hard'?ri(2,6):ri(1,4),r1=nz(-6,6),r2=nz(-6,6),b=-a*(r1+r2),c=a*r1*r2,D=b*b-4*a*c;return{q:a+'x² '+signTerm(b)+'x '+signTerm(c)+' = 0 ni yeching.',goal:'Kvadrat tenglama ildizlarini toping.',answer:['x='+r1+','+r2,r1+','+r2,'x1='+r1+',x2='+r2,'x1='+r2+',x2='+r1],hints:['D=b²−4ac.','D='+D+', √D='+Math.sqrt(D)+'.'],strategy:'x=(-b±√D)/(2a).',steps:['a='+a+', b='+b+', c='+c+'.','D='+D+'.','x=(-('+b+')±'+Math.sqrt(D)+')/'+(2*a)+'.','x='+r1+' yoki '+r2+'.'],pattern:'Diskriminant orqali universal yechim.',mistake:'−4ac ishorasi.',alternative:'Ildizlar butun bo‘lsa Vieta bilan tekshiring.'}}
function makeSequence(d){const a1=ri(-5,10),diff=d==='hard'?nz(-8,8):ri(2,7),n=d==='easy'?ri(8,15):d==='medium'?ri(15,30):ri(30,60),ans=a1+(n-1)*diff;return{q:a1+', '+(a1+diff)+', '+(a1+2*diff)+', ... ketma-ketlikning '+n+'-hadini toping.',goal:'Arifmetik progressiya formulasidan foydalaning.',answer:[String(ans),'a'+n+'='+ans],hints:['Ayirma d='+diff+'.','aₙ=a₁+(n−1)d.'],strategy:'Doimiy ayirmani topib umumiy formulaga qo‘ying.',steps:['a₁='+a1+', d='+diff+'.','a'+n+'='+a1+'+('+n+'−1)·'+diff+'.','a'+n+'='+ans+'.'],pattern:'Doimiy ayirma.',mistake:'n o‘rniga n−1 ni unutish.',alternative:'Rekursiv hisoblash mumkin, lekin sekinroq.'}}
function makeFunction(d){const a=d==='hard'?nz(-5,5):ri(1,4),b=nz(-6,6),c=nz(-8,8),x=d==='easy'?ri(1,4):nz(-5,5),ans=a*x*x+b*x+c;return{q:'f(x)='+a+'x² '+signTerm(b)+'x '+signTerm(c)+' bo‘lsa, f('+x+') ni toping.',goal:'Argumentni to‘liq almashtiring.',answer:[String(ans),'f('+x+')='+ans],hints:['Har bir x o‘rniga '+x+' yozing.','Darajani avval hisoblang.'],strategy:'Substitution: f('+x+')='+a+'·('+x+')²+'+b+'·('+x+')+'+c+'.',steps:['x='+x+' ni qo‘yamiz.','='+a+'·'+(x*x)+' + '+(b*x)+' + '+c+'.','='+ans+'.'],pattern:'Funksiya qiymatini hisoblash.',mistake:'Manfiy x ni qavssiz kvadratga oshirish.',alternative:'Jadval yoki grafik bilan tekshirish mumkin.'}}
function generateProblem(t,d){return t==='factor'?makeFactor(d):t==='quadratic'?makeQuadratic(d):t==='sequence'?makeSequence(d):makeFunction(d)}
let topic='factor',current=null,hintIndex=0,stepIndex=0;const session={correct:0,attempts:0,hints:0};
document.querySelectorAll('.topic').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.topic').forEach(x=>x.classList.remove('active'));b.classList.add('active');topic=b.dataset.topic;newProblem()}));
const norm=s=>String(s).toLowerCase().replace(/\s+/g,'').replace(/−/g,'-').replace(/²/g,'^2');
function newProblem(){const d=document.getElementById('difficulty')?.value||'medium';const p=generateProblem(topic,d);current=p;hintIndex=0;stepIndex=0;document.getElementById('problem-topic').textContent=document.querySelector('.topic.active').textContent;document.getElementById('problem-text').textContent=p.q;document.getElementById('problem-goal').textContent=p.goal;document.getElementById('attempt').value='';document.getElementById('feedback').className='feedback';document.getElementById('feedback').textContent='Avval o‘zingiz urinib ko‘ring.';document.getElementById('hints').innerHTML='<div class="empty">Hint so‘ramaguningizcha ochilmaydi.</div>';document.getElementById('strategy').innerHTML='<div class="empty">Qadam so‘rang.</div>';document.getElementById('steps').innerHTML='<div class="empty">To‘liq yechim yoki qadamlarni oching.</div>';document.getElementById('pattern').textContent=p.pattern;document.getElementById('mistake').textContent=p.mistake;document.getElementById('alternative').textContent=p.alternative}
function checkAttempt(){if(!current)return;session.attempts++;const a=norm(document.getElementById('attempt').value),ok=current.answer.some(x=>norm(x)===a),box=document.getElementById('feedback');if(ok)session.correct++;renderSession();box.className='feedback '+(ok?'good':'warn');box.innerHTML=ok?'<b>To‘g‘ri.</b> Endi yechim strategiyasini so‘z bilan tushuntirib bera olsangiz, mavzu ancha mustahkam bo‘ladi.':'<b>Hali mos kelmadi.</b> Xato javob — signal. Hintdan foydalanib qayerda burilish kerakligini toping.'}
function showHint(){if(!current)return;session.hints++;renderSession();hintIndex=Math.min(hintIndex+1,current.hints.length);document.getElementById('hints').innerHTML=current.hints.slice(0,hintIndex).map((h,i)=>'<div class="hint-item"><b>Hint '+(i+1)+':</b> '+h+'</div>').join('')}
function showNextStep(){if(!current)return;document.getElementById('strategy').innerHTML='<div class="hint-item"><b>Strategiya:</b> '+current.strategy+'</div>';stepIndex=Math.min(stepIndex+1,current.steps.length);document.getElementById('steps').innerHTML=current.steps.slice(0,stepIndex).map((s,i)=>'<div class="step-item"><b>'+(i+1)+'-qadam:</b> '+s+'</div>').join('')}
function showSolution(){if(!current)return;stepIndex=current.steps.length;document.getElementById('strategy').innerHTML='<div class="hint-item"><b>Strategiya:</b> '+current.strategy+'</div>';document.getElementById('steps').innerHTML=current.steps.map((s,i)=>'<div class="step-item"><b>'+(i+1)+'-qadam:</b> '+s+'</div>').join('')}
function renderSession(){document.getElementById('score-correct').textContent=session.correct;document.getElementById('score-attempts').textContent=session.attempts;document.getElementById('score-hints').textContent=session.hints}
function resetSession(){session.correct=session.attempts=session.hints=0;renderSession()}
newProblem();renderSession();