const bank={
factor:[
{q:'x² + 5x + 6 ni ko‘paytuvchilarga ajrating.',goal:'Ikki binom ko‘paytmasi ko‘rinishiga keltiring.',answer:['(x+2)(x+3)','(x+3)(x+2)'],hints:['Yig‘indisi 5, ko‘paytmasi 6 bo‘lgan ikki sonni qidiring.','Bu sonlar 2 va 3.'],strategy:'x²+bx+c da m+n=b va mn=c bo‘ladigan m,n topiladi.',steps:['m+n=5 va mn=6 shartlarni yozamiz.','2+3=5 va 2·3=6.','x²+5x+6=(x+2)(x+3).'],pattern:'Kvadrat uchhad uchun yig‘indi/ko‘paytma juftligini tanish.',mistake:'Faqat ko‘paytmasi 6 bo‘lgan juftni tanlab, yig‘indini tekshirmaslik.',alternative:'Butun juftlik topilmasa diskriminant yoki ildizlardan foydalanish mumkin.'},
{q:'4x² - 9 ni ko‘paytuvchilarga ajrating.',goal:'Qisqa ko‘paytirish formulasini taning.',answer:['(2x-3)(2x+3)','(2x+3)(2x-3)'],hints:['Bu ikki kvadrat ayirmasiga o‘xshaydi.','a²-b²=(a-b)(a+b).'],strategy:'4x²=(2x)² va 9=3².',steps:['4x²−9=(2x)²−3².','a²−b²=(a−b)(a+b).','Natija: (2x−3)(2x+3).'],pattern:'Ikki kvadrat ayirmasi.',mistake:'a²−b² ni (a−b)² deb yuborish.',alternative:'Agar hadlar kvadrat bo‘lmasa umumiy ko‘paytuvchini ajrating.'}],
quadratic:[
{q:'x² - 7x + 12 = 0 tenglamani yeching.',goal:'Ildizlarni toping.',answer:['x=3,4','3,4','x1=3,x2=4','x1=4,x2=3'],hints:['Ko‘paytmasi 12, yig‘indisi -7 bo‘lgan sonlar kerak.','-3 va -4 ni sinang.'],strategy:'Tenglamani (x-a)(x-b)=0 ko‘rinishga keltirish mumkin.',steps:['x²−7x+12=(x−3)(x−4).','Ko‘paytma 0 bo‘lsa kamida bir ko‘paytuvchi 0.','x=3 yoki x=4.'],pattern:'Butun ildizli kvadrat tenglama.',mistake:'Ildizlar ishorasini ko‘paytuvchilardagi ishora bilan adashtirish.',alternative:'Ajralmasa D=b²−4ac formulasiga o‘ting.'},
{q:'2x² + x - 3 = 0 ni yeching.',goal:'Kvadrat tenglama ildizlarini toping.',answer:['x=1,-1.5','1,-1.5','x1=1,x2=-1.5'],hints:['D=b²−4ac ni hisoblang.','D=25, √D=5.'],strategy:'Umumiy kvadrat formula x=(-b±√D)/(2a).',steps:['a=2,b=1,c=−3.','D=1−4·2·(−3)=25.','x=(-1±5)/4.','x₁=1, x₂=−3/2.'],pattern:'Ajratish qiyin bo‘lsa diskriminant universal usul.',mistake:'c manfiy bo‘lganda −4ac ishorasini xato qilish.',alternative:'Vieta orqali ham tekshirish mumkin.'}],
sequence:[
{q:'2, 5, 8, 11, ... ketma-ketlikning 20-hadini toping.',goal:'Arifmetik progressiya formulasidan foydalaning.',answer:['59','a20=59'],hints:['Ayirma doim 3.','aₙ=a₁+(n−1)d.'],strategy:'Avval progressiya turini va d ni aniqlang.',steps:['a₁=2, d=3.','a₂₀=2+(20−1)·3.','a₂₀=59.'],pattern:'Doimiy ayirma → arifmetik progressiya.',mistake:'n o‘rniga n−1 ni unutish.',alternative:'Rekursiv qo‘shib borish mumkin, lekin formula tezroq.'}],
function:[
{q:'f(x)=2x²−3x+1 bo‘lsa, f(2) ni toping.',goal:'x o‘rniga berilgan sonni to‘g‘ri qo‘ying.',answer:['3','f(2)=3'],hints:['Har bir x o‘rniga 2 yozing.','2·2²−3·2+1.'],strategy:'Funksiya qiymati — formuladagi argumentni berilgan qiymat bilan almashtirish.',steps:['f(2)=2·(2²)−3·2+1.','=8−6+1.','=3.'],pattern:'Argumentni to‘liq almashtirish.',mistake:'Darajani yoki manfiy ishorani noto‘g‘ri qo‘llash.',alternative:'Jadval tuzib ham tekshirish mumkin.'}]
};
let topic='factor',current=null,hintIndex=0,stepIndex=0;
document.querySelectorAll('.topic').forEach(b=>b.addEventListener('click',()=>{document.querySelectorAll('.topic').forEach(x=>x.classList.remove('active'));b.classList.add('active');topic=b.dataset.topic;newProblem()}));
const norm=s=>String(s).toLowerCase().replace(/\s+/g,'').replace(/−/g,'-').replace(/²/g,'^2');
function newProblem(){const arr=bank[topic],p=arr[Math.floor(Math.random()*arr.length)];current=p;hintIndex=0;stepIndex=0;document.getElementById('problem-topic').textContent=document.querySelector('.topic.active').textContent;document.getElementById('problem-text').textContent=p.q;document.getElementById('problem-goal').textContent=p.goal;document.getElementById('attempt').value='';document.getElementById('feedback').className='feedback';document.getElementById('feedback').textContent='Avval o‘zingiz urinib ko‘ring.';document.getElementById('hints').innerHTML='<div class="empty">Hint so‘ramaguningizcha ochilmaydi.</div>';document.getElementById('strategy').innerHTML='<div class="empty">Qadam so‘rang.</div>';document.getElementById('steps').innerHTML='<div class="empty">To‘liq yechim yoki qadamlarni oching.</div>';document.getElementById('pattern').textContent=p.pattern;document.getElementById('mistake').textContent=p.mistake;document.getElementById('alternative').textContent=p.alternative}
function checkAttempt(){if(!current)return;const a=norm(document.getElementById('attempt').value),ok=current.answer.some(x=>norm(x)===a),box=document.getElementById('feedback');box.className='feedback '+(ok?'good':'warn');box.innerHTML=ok?'<b>To‘g‘ri.</b> Endi yechim strategiyasini so‘z bilan tushuntirib bera olsangiz, mavzu ancha mustahkam bo‘ladi.':'<b>Hali mos kelmadi.</b> Xato javob — signal. Hintdan foydalanib qayerda burilish kerakligini toping.'}
function showHint(){if(!current)return;hintIndex=Math.min(hintIndex+1,current.hints.length);document.getElementById('hints').innerHTML=current.hints.slice(0,hintIndex).map((h,i)=>'<div class="hint-item"><b>Hint '+(i+1)+':</b> '+h+'</div>').join('')}
function showNextStep(){if(!current)return;document.getElementById('strategy').innerHTML='<div class="hint-item"><b>Strategiya:</b> '+current.strategy+'</div>';stepIndex=Math.min(stepIndex+1,current.steps.length);document.getElementById('steps').innerHTML=current.steps.slice(0,stepIndex).map((s,i)=>'<div class="step-item"><b>'+(i+1)+'-qadam:</b> '+s+'</div>').join('')}
function showSolution(){if(!current)return;stepIndex=current.steps.length;document.getElementById('strategy').innerHTML='<div class="hint-item"><b>Strategiya:</b> '+current.strategy+'</div>';document.getElementById('steps').innerHTML=current.steps.map((s,i)=>'<div class="step-item"><b>'+(i+1)+'-qadam:</b> '+s+'</div>').join('')}
newProblem();